# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linke_vision.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='linke_vision.proto',
  package='linke_vision',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12linke_vision.proto\x12\x0clinke_vision\"6\n\x04\x46ile\x12\x11\n\textension\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\r\x12\r\n\x05\x62ytes\x18\x03 \x01(\x0c\"Q\n\rDetectObjects\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x16percentage_probability\x18\x02 \x01(\x02\x12\x12\n\nbox_points\x18\x03 \x03(\x05\"\x18\n\x06Result\x12\x0e\n\x06status\x18\x01 \x01(\x05\"c\n\x13\x44\x65tectObjects4Image\x12!\n\x05image\x18\x01 \x01(\x0b\x32\x12.linke_vision.File\x12)\n\x04\x64\x65ts\x18\x02 \x03(\x0b\x32\x1b.linke_vision.DetectObjects2\xaf\x01\n\x0bLinkeVision\x12J\n\x0fObjectDetection\x12!.linke_vision.DetectObjects4Image\x1a\x14.linke_vision.Result\x12T\n\x15ObjectDetectionStream\x12!.linke_vision.DetectObjects4Image\x1a\x14.linke_vision.Result(\x01\x30\x01\x62\x06proto3')
)




_FILE = _descriptor.Descriptor(
  name='File',
  full_name='linke_vision.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extension', full_name='linke_vision.File.extension', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='linke_vision.File.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='linke_vision.File.bytes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=90,
)


_DETECTOBJECTS = _descriptor.Descriptor(
  name='DetectObjects',
  full_name='linke_vision.DetectObjects',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='linke_vision.DetectObjects.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percentage_probability', full_name='linke_vision.DetectObjects.percentage_probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_points', full_name='linke_vision.DetectObjects.box_points', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=173,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='linke_vision.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='linke_vision.Result.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=199,
)


_DETECTOBJECTS4IMAGE = _descriptor.Descriptor(
  name='DetectObjects4Image',
  full_name='linke_vision.DetectObjects4Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='linke_vision.DetectObjects4Image.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dets', full_name='linke_vision.DetectObjects4Image.dets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=300,
)

_DETECTOBJECTS4IMAGE.fields_by_name['image'].message_type = _FILE
_DETECTOBJECTS4IMAGE.fields_by_name['dets'].message_type = _DETECTOBJECTS
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['DetectObjects'] = _DETECTOBJECTS
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['DetectObjects4Image'] = _DETECTOBJECTS4IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'linke_vision_pb2'
  # @@protoc_insertion_point(class_scope:linke_vision.File)
  })
_sym_db.RegisterMessage(File)

DetectObjects = _reflection.GeneratedProtocolMessageType('DetectObjects', (_message.Message,), {
  'DESCRIPTOR' : _DETECTOBJECTS,
  '__module__' : 'linke_vision_pb2'
  # @@protoc_insertion_point(class_scope:linke_vision.DetectObjects)
  })
_sym_db.RegisterMessage(DetectObjects)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'linke_vision_pb2'
  # @@protoc_insertion_point(class_scope:linke_vision.Result)
  })
_sym_db.RegisterMessage(Result)

DetectObjects4Image = _reflection.GeneratedProtocolMessageType('DetectObjects4Image', (_message.Message,), {
  'DESCRIPTOR' : _DETECTOBJECTS4IMAGE,
  '__module__' : 'linke_vision_pb2'
  # @@protoc_insertion_point(class_scope:linke_vision.DetectObjects4Image)
  })
_sym_db.RegisterMessage(DetectObjects4Image)



_LINKEVISION = _descriptor.ServiceDescriptor(
  name='LinkeVision',
  full_name='linke_vision.LinkeVision',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=303,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='ObjectDetection',
    full_name='linke_vision.LinkeVision.ObjectDetection',
    index=0,
    containing_service=None,
    input_type=_DETECTOBJECTS4IMAGE,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ObjectDetectionStream',
    full_name='linke_vision.LinkeVision.ObjectDetectionStream',
    index=1,
    containing_service=None,
    input_type=_DETECTOBJECTS4IMAGE,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LINKEVISION)

DESCRIPTOR.services_by_name['LinkeVision'] = _LINKEVISION

# @@protoc_insertion_point(module_scope)
