# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import linke_vision_pb2 as linke__vision__pb2


class LinkeVisionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ObjectDetection = channel.unary_unary(
        '/linke_vision.LinkeVision/ObjectDetection',
        request_serializer=linke__vision__pb2.DetectObjects4Image.SerializeToString,
        response_deserializer=linke__vision__pb2.Result.FromString,
        )
    self.ObjectDetectionStream = channel.stream_stream(
        '/linke_vision.LinkeVision/ObjectDetectionStream',
        request_serializer=linke__vision__pb2.DetectObjects4Image.SerializeToString,
        response_deserializer=linke__vision__pb2.Result.FromString,
        )


class LinkeVisionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ObjectDetection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ObjectDetectionStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LinkeVisionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ObjectDetection': grpc.unary_unary_rpc_method_handler(
          servicer.ObjectDetection,
          request_deserializer=linke__vision__pb2.DetectObjects4Image.FromString,
          response_serializer=linke__vision__pb2.Result.SerializeToString,
      ),
      'ObjectDetectionStream': grpc.stream_stream_rpc_method_handler(
          servicer.ObjectDetectionStream,
          request_deserializer=linke__vision__pb2.DetectObjects4Image.FromString,
          response_serializer=linke__vision__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'linke_vision.LinkeVision', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
